#!/usr/bin/env bash

TEMP_DIR=/tmp/release_fypo.$RANDOM.$$

rm -rf $TEMP_DIR
mkdir $TEMP_DIR

cd $TEMP_DIR

svn checkout https://pombase.svn.sourceforge.net/svnroot/pombase/phenotype_ontology
cd phenotype_ontology

OUT_DIR=`pwd`/oort.tmp

FYPO_OBO=`pwd`/fypo_edit.obo
GO_OBO=http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/editors/gene_ontology_write.obo
PATO_OBO=http://obo.cvs.sourceforge.net/viewvc/obo/obo/ontology/phenotype/quality.obo
CHEBI_OBO=http://obo.cvs.sourceforge.net/viewvc/obo/obo/ontology/chemical/chebi.obo
CELL_TYPE_OBO=http://obo.cvs.sourceforge.net/viewvc/obo/obo/ontology/anatomy/cell_type/cell.edit.obo
BRENDA_TISSUE_OBO=http://www.brenda-enzymes.info/ontology/tissue/tree/update/update_files/BrendaTissueOBO

/usr/local/OBOReleaseManager/scripts/ontology-release-runner -outdir $OUT_DIR \
    --no-subsets -reasoner elk --simple \
    $FYPO_OBO $GO_OBO $PCO_OBO $CHEBI_OBO $CELL_TYPE_OBO $BRENDA_TISSUE_OBO \
    > ontology-release-runner.log 2>&1

release_path=$OUT_DIR/releases/*
release=`basename $release_path`

new_release_dir=./releases/$release
svn mkdir $new_release_dir ||
  (echo "error: can't make new release directory: $new_release_dir" 1>&2; exit 1)

files_to_move="fypo-merged.obo fypo-simple.obo"

for file in $files_to_move
do
  mv $release_path/$file $new_release_dir/ ||
    (echo failed to move $file to release directory 1>&2; exit 1)
  svn add $new_release_dir/$file
done

svn commit -m 'FYPO release' releases

rm -rf $TEMP_DIR
