#!/usr/bin/env bash

if [ $# = 0 ]
then
    echo usage: $0 sourceforge_username 1>&2
    exit 1
fi

# this is a dirty hack: DNS problems at SysBiol mean that sometimes
# the lookup of obo.cvs.sourceforge.net by owltools falls.  If we
# query before we start it works.  Sigh.
dig obo.cvs.sourceforge.net > /dev/null 2>&1

username=$1

CURRENT_DIR=`pwd`

cd /data/pombase/sources/phenotype_ontology

svn update

OUT_DIR=`pwd`/oort.tmp
rm -rf $OUT_DIR

OORT_LOG_FILE=$CURRENT_DIR/ontology-release-runner.log

FYPO_OBO=`pwd`/fypo_edit.obo
CHEBI_OBO=http://build.berkeleybop.org/job/build-chebi/lastSuccessfulBuild/artifact/main/chebi-simple.obo # special non-purl location for super-simplified chebi file (is_a only)
BRENDA_TISSUE_OBO=/data/pombase/sources/BTO_is-a_only.obo # special location for locally massaged file (is_a only)
GO_OBO=http://purl.obolibrary.org/obo/go.obo
CELL_TYPE_OBO=http://purl.obolibrary.org/obo/cl.obo
PATO_OBO=http://purl.obolibrary.org/obo/pato.obo
SO_OBO=http://purl.obolibrary.org/obo/so-xp.obo

# old URLs noted for reference, and in case anything goes awry with PURLs
# GO_OBO=http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/editors/gene_ontology_write.obo
# CELL_TYPE_OBO=http://obo.cvs.sourceforge.net/viewvc/obo/obo/ontology/anatomy/cell_type/cell.edit.obo
# PATO_OBO=http://obo.cvs.sourceforge.net/viewvc/obo/obo/ontology/phenotype/quality.obo
# SO_OBO=http://song.svn.sourceforge.net/viewvc/song/trunk/so-xp.obo

echo running ontology-release-runner
/usr/local/OBOReleaseManager-0.4.0/scripts/ontology-release-runner -outdir $OUT_DIR \
    --no-subsets -reasoner elk --simple \
    $FYPO_OBO $GO_OBO $PCO_OBO $CHEBI_OBO $CELL_TYPE_OBO $BRENDA_TISSUE_OBO $SO_OBO \
    > $OORT_LOG_FILE 2>&1

release_path=`echo $OUT_DIR/releases/*`
release=`basename $release_path`

if [ ! -e $release_path ]
then
  echo "error: no directories found in $OUT_DIR/releases/ - check $OORT_LOG_FILE" 1>&2
  exit 1
fi

grep -v '^relationship: has_part' $release_path/fypo-simple.obo | 
  grep -v '^relationship: inheres_in' | grep -v '^synonymtypedef: ' > $release_path/fypo-basic.obo

files_to_move="fypo.obo fypo-merged.obo fypo-simple.obo fypo-basic.obo"

for file in $files_to_move
do
  mv $release_path/$file releases/latest
done

new_release_dir=./releases/$release
svn cp releases/latest $new_release_dir ||
  (echo "error: can't make new release directory: $new_release_dir" 1>&2; exit 1)

svn commit --username=$username -m 'FYPO release' releases

cp $new_release_dir/* /var/www/pombase/ontologies/fypo/latest/
