name: Run release
on:
  workflow_dispatch:


jobs:

  run-release:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.4
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: work around permission issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Update release files
        run: cd src/ontology/ && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' GITHUB_ACTION=true synonyms fix_quality_issue clear_obsoletes prepare_release_fast normalise_xsd_string && cd ../../
      - name: Run release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: true
          tag_name: v${{ steps.date.outputs.date }}
          files: |
            fyeco.obo
            fypo-base.json
            fypo-base.obo
            fypo-base.owl
            fypo-full.json
            fypo-full.obo
            fypo-full.owl
            fypo-non-classified.json
            fypo-non-classified.obo
            fypo-non-classified.owl
            fypo-simple-pombase.obo
            fypo-simple.json
            fypo-simple.obo
            fypo-simple.owl
            fypo.json
            fypo.obo
            fypo.owl
            reports/fypo-edit.owl-obo-report.tsv

