name: 'Ensure normalised_xsd_string is ran'

on:
  # Triggers the workflow on pull request events for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    container: obolibrary/odklite:v1.4
    steps:
      # Checks-out the branch being merged into master in the root directory
      # The ontology obo file path will be: src/ontology/fypo-edit.owl
      - uses: actions/checkout@v3
      - name: Ensure normalised_xsd_string is ran
        run: |
            cd src/ontology;
            sed -i -E "s/Annotation[(](oboInOwl[:]hasDbXref [\"][^\"]*[\"])[)]/Annotation(\1^^xsd:string)/g" fypo-edit.owl;
            git diff --exit-code;
            # If there are no changes, exit with zero
            if [ $? -eq 0 ]; then
                exit 0
            fi

            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git commit -am "Ensure normalised_xsd_string is ran"
            git push

            # Post a comment in the PR saying that the normalised_xsd_string has been ran
            PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
            curl \
                -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments \
                -d '{"body": "The normalised_xsd_string has been ran. Please review the changes."}'
