name: Refresh imports
on:
  workflow_dispatch:

jobs:
  imports:
    runs-on: ubuntu-latest
    container: obolibrary/odklite:v1.5.4

    steps:
      # Checks-out current branch - fetch-depth 0 so that create-pull-request
      # is faster
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: work around permission issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Refreshing imports
        run: cd src/ontology/ && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx10G' GITHUB_ACTION=true refresh-imports

      - name: Refreshing components
        run: cd src/ontology/ && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx10G' GITHUB_ACTION=true ../patterns/definitions.owl

      # - name: Remove patternized classes
      #   run: cd src/ontology/ && docker run -v $PWD/../../:/work -w /work/src/ontology -e ROBOT_JAVA_ARGS='-Xmx10G' -e JAVA_OPTS='-Xmx10G' --rm obolibrary/odklite make GITHUB_ACTION=true remove_patternised_classes

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update imports and components
          title: 'Update all imports and components'
          body: |
            Updates all imports and components.
          assignees: manulera, ValWood
